# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0728e73551cdfbd67aa5db7abaf22588"
application_url = "https://example.com"
embedded = true
name = "Codex Ops Admin API"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_products,write_products,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
